name: Publish Crate

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"


permissions:
  contents: write
  id-token: write

jobs:
  build-and-upload:
    name: Build and Upload for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: alter-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: alter-macos-arm64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: alter-windows-x86_64.exe
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Temporarily modify the rust toolchain version
        run: rustup override set stable
        
      - name: Output rust version for educational purposes
        run: rustup --version

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }} --no-default-features --features tls-rustls

      - name: Prepare binary for upload (Windows)
        if: runner.os == 'Windows'
        run: |
          cd target/${{ matrix.target }}/release
          mv alter.exe ${{ matrix.artifact_name }}
        shell: pwsh
      
      - name: Prepare binary for upload (UNIX)
        if: runner.os != 'Windows'
        run: |
          cd target/${{ matrix.target }}/release
          mv alter ${{ matrix.artifact_name }}

      - name: Upload to Release
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe
        with:
          files: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  publish-to-cargo:
    runs-on: ubuntu-latest

    container:
      image: rust:latest

    steps:
      - name: 🗄️ Checkout repository
        uses: actions/checkout@v4

      - name: 🔒 Authorize with Trusted Publishing
        uses: rust-lang/crates-io-auth-action@v1
        id: auth

      - name: 📦 Publish Crate
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
